import BasePage from '@/app/ui/BasePage/BasePage';
import '@/app/ui/styles/app.scss';
import '@/app/ui/styles/reset.scss';
import '@/app/ui/styles/structure.scss';
import '@/app/ui/styles/tags.scss';
import '@/app/ui/styles/variables.scss';
import type { Metadata } from 'next';
import { Fira_Sans } from 'next/font/google';

const firaSans = Fira_Sans({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={firaSans.className}><BasePage>{children}</BasePage></body>
    </html>
  );
}
